export enum RoutesAccountStack {
  ACCOUNT = 'ACCOUNT',
  PROFILE = 'PROFILE',
  EDIT_PROFILE = 'EDIT_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  ORDER = 'ORDER',
  ORDER_DETAILS = 'ORDER_DETAILS',
}
