export enum RoutesMainStack {
  ACCOUNT_STACK = 'ACCOUNT_STACK',
  AUTH_STACK = 'AUTH_STACK',
  CART_STACK = 'CART_STACK',
  COMMON_STACK = 'COMMON_STACK',
  EXPLORE_STACK = 'EXPLORE_STACK',
  NOTIFICATION_STACK = 'NOTIFICATION_STACK',
  OFFER_STACK = 'OFFER_STACK',
  PAYMENT_STACK = 'PAYMENT_STACK',
  PRODUCT_DETAIL_STACK = 'PRODUCT_DETAIL_STACK',
  SEARCH_STACK = 'SEARCH_STACK',
  TAB_STACK = 'TAB_STACK',
}
