export enum RoutesNotificationStack {
  NOTIFICATIONS = 'NOTIFICATIONS',
  OFFER_NOTIFICATION = 'OFFER_NOTIFICATION',
  FEED_NOTIFICATION = 'FEED_NOTIFICATION',
  ACTIVITY_NOTIFICATION = 'ACTIVITY_NOTIFICATION',
}
