export enum RoutesPaymentStack {
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  CARD = 'CARD',
  PURCHASE_SUCCESS = 'PURCHASE_SUCCESS',
  ADD_CARD = 'ADD_CARD',
  COMPLETED_CARD = 'COMPLETED_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  CHECK_CARD = 'CHECK_CARD',
}
